// flow-typed signature: 5a0c6758c67cfc3e9471d1f42d53124d
// flow-typed version: <<STUB>>/react-device-detect_v^1.5.9/flow_v0.80.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-device-detect'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-device-detect' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'react-device-detect/dist/index' {
  declare module.exports: any;
}

declare module 'react-device-detect/webpack.config' {
  declare module.exports: any;
}

// Filename aliases
declare module 'react-device-detect/dist/index.js' {
  declare module.exports: $Exports<'react-device-detect/dist/index'>;
}
declare module 'react-device-detect/webpack.config.js' {
  declare module.exports: $Exports<'react-device-detect/webpack.config'>;
}
